
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
    }
}

apply plugin: 'com.android.application'

android {

//    useLibrary 'org.apache.http.legacy'

    dexOptions {
        javaMaxHeapSize "4g"
    }

    repositories {
        flatDir {
            dirs 'libs'
        }
    }

    compileSdkVersion 22
    buildToolsVersion '23.0.2'

    def versionPropsFile = file('version.properties')

    if (versionPropsFile.canRead()) {
        def Properties versionProps = new Properties()

        versionProps.load(new FileInputStream(versionPropsFile))

        def code = versionProps['VERSION_CODE'].toInteger() + 1

        versionProps['VERSION_CODE']=code.toString()
        versionProps.store(versionPropsFile.newWriter(), null)

        defaultConfig {
            applicationId "com.flipflashcards.FFC_Android_dev"
            minSdkVersion 16
            targetSdkVersion 22
            versionCode 6921
            versionName '2.0'
            multiDexEnabled true
        }
    }
    else {
        throw new GradleException("Could not read version.properties!")
    }



    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt','proguard-fresco.pro'
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt','proguard-fresco.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }
}


allprojects {
    repositories {
        jcenter()

        maven { url "https://jitpack.io" }
    }
}


repositories {
    mavenCentral()
}


dependencies {
    compile 'com.android.support:support-v4:22.1.1'
    compile 'com.android.support:support-annotations:23.0.0'

    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'
    testCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'

    compile 'com.dropbox.core:dropbox-core-sdk:2.1.2'
    
    compile files('libs/json_simple-1.1.jar')
    compile files('libs/aws-android-sdk-cognito-2.2.1.jar')
    compile files('libs/aws-android-sdk-core-2.2.1.jar')
    compile files('libs/aws-android-sdk-s3-2.2.1.jar')
    compile files('libs/aws-android-sdk-sdb-2.2.1.jar')
    compile files('libs/httpmime-4.0.3.jar')
    compile files('libs/json_simple-1.1.jar')
    compile files('libs/libGoogleAnalyticsV2.jar')
    //compile files('libs/simple-social-sharing-1.0.1.jar')
    compile files('libs/zip4j_1.3.2.jar')
    compile 'asia.ivity.android:drag-sort-listview:1.0@aar'
    compile project(':Viewflow')
    compile project(':NewQuickAction3D')
    compile 'com.isseiaoki:simplecropview:1.0.9'
    compile(name: 'android_target_tooltip_ccaa_22112014', ext: 'aar')
    compile 'com.nineoldandroids:library:+'
    compile 'com.makeramen:roundedimageview:2.0.1'
    compile 'cn.pedant.sweetalert:library:1.3'
    compile project(':discreteSeekBar')
    compile 'com.facebook.stetho:stetho:1.1.0'
    compile project(':simpleSocialSharing')
    compile 'me.relex:circleindicator:1.1.3@aar'
    compile 'com.facebook.rebound:rebound:0.3.8'
    compile 'com.github.lzyzsd:circleprogress:1.1.0@aar'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'net.soulwolf.widget:ratiolayout:1.0.0'
    compile 'com.facebook.android:facebook-android-sdk:4.6.0'
    compile files('libs/ParseCrashReporting-1.8.3.jar')
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.daimajia.easing:library:1.0.1@aar'
    compile 'com.daimajia.androidanimations:library:1.1.3@aar'
    compile 'commons-io:commons-io:+'
    compile 'com.github.orhanobut:hawk:1.22'
    compile project(':mediapicker')
    compile project(':lvl')

    //https://github.com/anjlab/android-inapp-billing-v3
    compile 'com.anjlab.android.iab.v3:library:1.0.+'

    compile ('com.facebook.fresco:fresco:0.13.0+'){
        exclude group: 'com.parse.bolts', module: 'bolts-applinks';
        exclude module: 'bolts-android';
            exclude group: 'com.parse.bolts', module: 'bolts-tasks';
    }

    compile ('com.facebook.fresco:animated-gif:0.13.0+'){
        exclude group: 'com.parse.bolts', module: 'bolts-applinks';
        exclude module: 'bolts-android';
        exclude group: 'com.parse.bolts', module: 'bolts-tasks';
    }



    //Google drive related

    compile 'com.google.http-client:google-http-client-gson:1.22.0' exclude module: 'httpclient'
    compile 'com.google.api-client:google-api-client-android:1.22.0' exclude module: 'httpclient'
    compile 'com.google.apis:google-api-services-drive:v3-rev52-1.22.0' exclude module: 'httpclient'

    //avoid 64k max method issue: https://developer.android.com/studio/build/multidex.html
    compile 'com.android.support:multidex:1.0.1'
}

apply plugin: 'com.google.gms.google-services'


